spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db_url}
    username: ${db_user}
    password: ${db_password}
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect